<?php include "routes.php"; ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $projectName ?>  |  Regulatory Compliance </title>
    <?php include "assetCss.php"; ?>
  </head>
  <body
>    <?php include "header.php"; ?>
    <div class="innerpageBanner animated flipInX bannerimg-compliance">
      <!-- <img src="images/regulatory-compliance.png" alt="Regulatory Compliance"> -->
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center caption-container">
            <div class="caption-ovelay blue caption-box">
              <h3>
                  'Right First Time every time, Surpassing regulatory standards' 
              </h3>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?php include "news.php"; ?>
    <div class="container">
      <div class="row innerContent">
        <div class="col-md-3">
        <?php include "overview.php"; ?>
          <?php include "operation.php"; ?>
          <?php include "sidebarSlider.php"; ?>          
          
        </div>
        <div class="col-md-9">
        <h3>Regulatory Compliance</h3>
          <!--           <h1>Heading One</h1>
          <h2>Heading Two</h2> -->
          <!--  <h3>GLOBAL QUALITY </h3> -->
              <p align="center">
                <strong>'Right First Time every time'.</strong>
              </p>
          <p>
            The global competition demands faster turn around from product development to market access. As organization success is usually function of time, efforts and finance in pharmaceutical environment, this regulatory time gap is very critical as it can strain the company revenue system with complicated regulatory pathways in every targeted market that take over few months to complete and can often go on to several years if not approached meticulously with detailed insights.  GBennetti Regulatory Affairs team keeps track of the ever-changing legislation in all the regions in which the company intends to market its products.
            <br />
            <br />
          </p>
          <p>
            'Right First Time every time ' pathway of our Regulatory Affairs plays a crucial role in coordinating scientific endeavor with regulatory demands throughout the life of the product, helping to maximize the cost-effective use of the company's resources. The regulatory cell also advises on the legal and scientific restraints and requirements as well as collect and evaluate the scientific data generated by R&amp;D. Our Regulatory Affairs is capable of all types of regulatory submissions (Dossiers / ANDA / ANDS / CTD / e CTD) to any of the semi-regulated to highly regulated markets ensuring fast turn around in business.
            <br/>
            <br/>
          </p>
          <p>
            Medical services function hand in hand with regulatory affairs to ensure every product filing is adequate, accurate and legitimate in its data submission. Wherever required, medical services co-ordinate with CRO’s of acceptable global standards and perform pharmacokinetic, in-vitro/in-vivo correlation and bioequivalence studies to facilitate the introduction of generic or new drugs into the international market. They also facilitate the dosage form development by carrying out permeability studies for derma products and also proof of concept studies during development of differentiated and/or controlled release formulations. The team has strengths in pharmacokinetics, bio-statistics and bio-analytical work streams and has networked with few of the best clinical facilities and bio-analytical laboratories in the industry, which work as per international regulatory requirements, meeting strict GCP and GLP requirements.
            <br/>
            <br/>
          </p>
          <p>
            GBennetti’scompliance to global regulatory excellence facilitates its ambition of providing safe and efficacious healthcare products worldwide. The inherent design of global regulatory framework provides reassurance on patient safety and that the data provided to the regulators is of the highest standard quality, accuracy and integrity.
            <br/>
            <br/>
            <span>Capabilities:</span>
            <table class="table table-striped table-bordered dt-responsive nowrap bulk_action" cellspacing="0" width="100%">
              <thead>
                
              </thead>
              <tbody>
                <tr>
                  <td>
                    Compilation of dossier as per latest country specific guidelines
                    <ul>
                      <li>Common Technical Dossier (CTD/eCTD)</li>
                      <li>Asean Common Technical Dossier (ACTD) ANDA/ANDS</li>
                      <li>Country specific.</li>
                    </ul>
                  </td>
                  <td>Clinical trials, bio-availability & bioequivalencestudies , Validation data, Expert reports
                  </td>
                  <td>Rich experience of regulatory affairs across wide array of therapeutic segments (including human health, animal health and herbal range of products)</td>
                </tr>
                <tr>
                  <td>Drug master file (DMF) compilation for open      and closed parts</td>
                  <td> PSUR through registration activities </td>
                  <td>Regulatory track of ever-changing legislations across the globe and coalition with the eminent ministry of affairs</td>
                </tr>
                
                <tr>
                  <td>Medical writing &amp; clinical studies including
                    Preclinical studies like Toxicity, sub acute,
                    Acute Carcinogenicity, Teratology &amp;
                    Reproduction toxicity
                  </td>
                  <td>E-Filings to post-marketing regulatory obligations</td>
                  <td>Fast turn around times from concept to commercialization</td>
                </tr>
              </tbody>
            </table>
          </p>
          <!--<p class="text-center">
             <img src="images/comapliance.jpg"> 
          </p>-->
<?php include "usp.php"; ?>
<a href="promethus-augustus.php" class="pull-right">Next - Promethus <i class="glyphicon glyphicon-chevron-right"></i></a>
        </div>
      </div>
    </div>
    <?php include "footer.php"; ?>
    <?php include "assetJs.php"; ?>
